name: Portal CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    name: Build with gcc and test
    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:alexlarsson/flatpak
        sudo add-apt-repository ppa:alexlarsson/glib260
        sudo apt-get update
        sudo apt-get install -y libglib2.0 attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libcap-dev libattr1-dev libdw-dev libelf-dev \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-glib-dev libdconf-dev clang socat meson libdbus-1-dev
    - name: Check out xdg-desktop-portal
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build libportal dependency
      run: |
        git clone https://github.com/flatpak/libportal.git ./libportal
        pushd ./libportal
        git checkout master
        meson setup --prefix=/usr _build
        ninja -C _build
        sudo ninja -C _build install
        popd
    - name: Create logs dir
      run: mkdir test-logs
    - name: Configure xdg-desktop-portal
      # TODO: Enable gtk-doc builds
      run: ./autogen.sh
      env:
        CFLAGS: -fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -O2 -Wp,-D_FORTIFY_SOURCE=2
    - name: Build xdg-desktop-portal
      run: make -j $(getconf _NPROCESSORS_ONLN)
    - name: Run xdg-desktop-portal tests
      # TODO: Build with -j (currently ends up with hangs in the tests)
      run: make check
      env:
        ASAN_OPTIONS: detect_leaks=0 # Right now we're not fully clean, but this gets us use-after-free etc
    - name: Collect overall test logs on failure
      if: failure()
      run: mv test-suite.log test-logs/ || true
    - name: Collect individual test logs on cancel
      if: failure() || cancelled()
      run: mv tests/*.log test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: test logs
        path: test-logs

  clang:
    name: Build with clang
    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:alexlarsson/flatpak
        sudo add-apt-repository ppa:alexlarsson/glib260
        sudo apt-get update
        sudo apt-get install -y libglib2.0 attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libcap-dev libattr1-dev libdw-dev libelf-dev \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-glib-dev libdconf-dev clang
    - name: Check out xdg-desktop-portal
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure xdg-desktop-portal
      # We disable introspection because it fails with clang: https://bugzilla.redhat.com/show_bug.cgi?id=1543295
      run: ./autogen.sh --disable-introspection --disable-libportal
      env:
        CC: clang
        CFLAGS: -Werror=unused-variable
    - name: Build xdg-desktop-portal
      run: make -j $(getconf _NPROCESSORS_ONLN)
